farcasterxyz/contracts

- src/Namespace.sol
- test/Namespace.t.sol
The magic constant for the dutch auction decay incorrectly used 28,000 seconds for the 8-hour window, instead of the correct value of 28,800. 
Thanks to [@ncitron](https://github.com/ncitron)  and  [@blauyourmind](https://github.com/Blauyourmind) for catching this.
> fix: auction decay incorrectly calculated window size

- .gas-snapshot
- docs/docs.md
- script/NameRegistry.s.sol
- src/NameRegistry.sol
- test/MetaTx.t.sol
- test/NameRegistry.t.sol
- test/NameRegistryGasUsage.t.sol
- test/NameRegistryUpgrade.t.sol
- add `withdraw` which allows the treasurer to move funds to the vault
- change `reclaim` to move names to a new pool address
- rename owner to admin in all tests
- refactor tests to separate admin from default admin
> feat(NameRegistry): allow withdrawal of funds to a vault

- .gas-snapshot
- src/NameRegistry.sol
- test/NameRegistry.t.sol
- test/NameRegistryGasUsage.t.sol
The invite server should be able to pass the fids of the inviter and invitee into the trusted register method, which should in turn emit an on-chain invite event.
> feat(NameRegistry): trusted register should emit invite event

- .gas-snapshot
- src/BundleRegistry.sol
- test/BundleRegistry.t.sol
- test/BundleRegistryGasUsage.t.sol
Previously, BundleRegistry's `trustedRegister` and `partialTrustedRegister` required passing in the invitee for the Invite event. However, this is only known after calling IDRegistry during the call and cannot be provided ahead of time. This change no longer requires the parameter to be provided and populates it automatically. 
There are two ways this could have been implemented: 
1. Modifying IDRegistry's `register` and `trustedRegister` to return the id
2. Query the IDRegistry's idOf function between calls to fetch the id 
Option 1 was rejected because it added a fixed ~150 gas cost to all register calls for all time, while Option 2 only added ~800 gas to calls made during the invitation period.  While Option 1 adds greater composability for future actions that might want to do things …
> fix(BundleRegistry): invitee should be automatically attributed

- .husky/pre-commit
addresses #48 
Question: I noticed the CI is running "--match-contract Gas" which I have included here to keep it in line with the expected results. I see that we also have some tests that are specifically related to Gas usage. Is there a downside to running the snapshot for all tests?
> feat: add precommit hook to check if gas snapshots are up to date

- .gas-snapshot
- src/NameRegistry.sol
- test/NameRegistry.t.sol
Since the payment for bid, renew and register are now predictable overpayments will be unlikely. Save gas by checking if there is an overpayment before returning the funds. 
- register costs 151 less
- renew costs 189 less
- bid costs 151 less
Thanks to [@ncitron](https://github.com/ncitron), Matt Gleason, and [@blauyourmind](https://github.com/Blauyourmind) for identifying this.
> perf(NameRegistry): check for overpayment before returning funds

- src/NameRegistry.sol
Save gas by performing unchecked for-loop increments
> perf(NameRegistry): for-loop optimizations in tokenURI

- src/IdRegistry.sol
In `register`:
https://github.com/farcasterxyz/contracts/blob/80dde9b16ba09774d7500e24cded5fd88a71863e/src/IdRegistry.sol#L200
and, in `trustedRegister`:
https://github.com/farcasterxyz/contracts/blob/80dde9b16ba09774d7500e24cded5fd88a71863e/src/IdRegistry.sol#L223
=> `trustedOnly = 0` to call `register`.
`trustedOnly = 1` to call `trustedRegister`.
The comment over the the definition of `trustedOnly` conveyed the opposite.
https://github.com/farcasterxyz/contracts/blob/80dde9b16ba09774d7500e24cded5fd88a71863e/src/IdRegistry.sol#L141
Cheers,
Yash Karthik
> Correct comment explaining `trustedOnly`

- test/NameRegistry.t.sol
- test/NameRegistryUpgrade.t.sol
Avoid false positive warnings in solhint
Suppress warnings for intentionally empty tests and mark a constant correctly. 
> fix(NameRegistry): warnings in tests

- test/BundleRegistry.t.sol
- test/IdRegistry.t.sol
- test/NameRegistry.t.sol
- test/TestConstants.sol
BundleRegistry#testCannotRegisterIfIdRegistryEnabledNameRegistryDisabled BundleRegistry#testRegister
IdRegistry#testCancelRecoveryFromCustodyAddress
IdRegistry#testCancelRecoveryFromRecoveryAddress
IdRegistry#testCannotCompleteRecoveryIfNotRequested IdRegistry#testCannotCompleteRecoveryToAddressThatOwnsAnId IdRegistry#testRequestRecoveryOverridesPreviousRecovery IdRegistyry#testCompleteRecovery
NameRegistry#testCannotRegisterTheSameNameAgain
NameRegistry#testMakeCommitAfterReplayDelay
NameRegistry#testRegister
NameRegistry#testRegisterAfterUnpausing
NameRegistry#testRegisterWorksWhenAlreadyOwningAName
Fuzzing timestamps adds test coverage to ensure functionality is not inadvertently making assumptions.
Added some timestamp fuzzing to the tests.
> test: Add some timestamp fuzzing to test coverage

- docs/docs.md
match protocol [spec](https://github.com/farcasterxyz/protocol/blob/main/README.md#22-farcaster-names)
Contract also [implements](https://github.com/farcasterxyz/contracts/blob/767c94165f9b4ec3a08698fb842468bb2bd79347/src/NameRegistry.sol#L1075) the protocol fname regex forbidding hyphens in the first character
Inconsistencies in the docs are confusing for newcomers,
Fix out-dated contract docs to match protocol docs
This is a simple fix to the docs.
> docs(fname): regex to match protocol

- src/NameRegistry.sol
- test/NameRegistryUpgrade.t.sol
- test/Utils.sol
Bring naming conventions in line with recent changes to IdRegistry
- Rename RecoveryState.recoveryDestination to recoveryState.destination
- Rename RecoveryState.recoveryTs to RecoveryState.timestamp
> refactor(NameRegistry): rename struct properties in RecoveryState

- .github/workflows/ci.yml
- package.json
Speeds up tests by avoiding usage of yarn 
- Called forge fmt directly in CI
- Removed setup and restore of yarn packages in CI
- Removed unused yarn command
> ci: call forge-fmt directly instead of using yarn

- .github/workflows/ci.yml
Codecov bot is sometimes slow or unresponsive and coverage results aren't available at merge time
Use simpler actions from ScopeLift's security template that write results directly to PR.
> ci: use simple actions instead of codecov

- src/NameRegistry.sol
- test/NameRegistry.t.sol
Avoid checked math for statements that cannot underflow or overflow given constraints
Removed checks in reclaim() which reduces gas usage by ~300 for batch reclaims of 4
> perf(NameRegistry): reduce gas usage in reclaim with unchecked math

- test/NameRegistry.t.sol
Fix false positive error in fuzzing.
Remove pre existing contracts in our foundry environment from the fuzzer inputs for transfer targets
> test: fix fuzzer failures where one address collidied with exisiting contracts

- test/NameRegistry.t.sol
> test(NameRegistry): unicode string inputs for fnames

- test/IdRegistry.t.sol
This PR address issue https://github.com/farcasterxyz/contracts/issues/210 and adds 1 new test.
Adds `testFuzzTransferReregister` which test that an address that owns an fid can successfully transfer out the fid and register a new one .
If this is a relatively large or complex change, provide more details here that will help reviewers.
> test: add test register after transfer

- .gas-snapshot
- .rusty-hook.toml
- src/IdRegistry.sol
- test/IdRegistry/IdRegistry.t.sol
Users who perform a recovery or transfer will automatically lose their recovery address, which leads to more lost accounts. Not resetting the recovery address is a better experience that protects users. 
Recovery address is no longer reset when `transfer` or `recover` is called successfully
> feat(IdRegistry): don't reset recovery address on transfer

- src/Bundler.sol
- src/FnameResolver.sol
- src/IdRegistry.sol
- src/KeyRegistry.sol
- src/StorageRent.sol
- src/lib/TrustedCaller.sol
Run spellcheck over code to remove common errors.
See above
> chore: run spellcheck over code and comments

- docs/docs.md
- src/StorageRegistry.sol
- test/StorageRegistry/StorageRegistry.t.sol
The treasurer role has the ability to set the storage price which is a dangerous action since it can eliminate signup costs and make it easy for spammers to join the network. This change restricts that ability to just the owner account.  
- Don't allow treasurer role to set the storage price
If this is a relatively large or complex change, provide more details here that will help reviewers.
> feat(StorageRegistry): treasurer should not be able to set price

- Dockerfile.foundry
- docker-compose.yml
We're seeing issues where it appears qemu fails causing issues for the image provided by Foundry (which at time of writing is AMD only).
So that we don't need emulation, build image on the fly specific to the local system.
> chore: Use custom Docker image for local development

- script/LocalDeploy.s.sol
- src/KeyRegistry.sol
- test/KeyRegistry/KeyRegistryTestSuite.sol
- test/Utils.sol
The deployer can set an arbitrary `KeyRegistry.gracePeriod`, but we'd like to constrain this by hardcoding a fixed value. See #332.
Convert `gracePeriod` to a constant and remove this parameter from the `KeyRegistry` constructor.
Close #332
> fix(KeyRegistry): set fixed gracePeriod

- foundry.toml
- script/Deploy.s.sol
We made some recent changes to the `KeyRegistry` and `StorageRegistry` constructor args that weren't reflected in the deployment script. 
We have a [fork test](https://github.com/farcasterxyz/contracts/blob/main/test/Deploy/Deploy.t.sol) that's meant to run on CI to test the deploy script, but it turns out our `foundry.toml` was misconfigured and it was being skipped.
Update constructor args in `Deploy.s.sol`. Add an empty `no_match_path` rule to the Foundry CI profile to override the default and match all tests.
> fix: update deploy scripts

- Dockerfile.foundry
This doesn't seem to work on other people's machines, but it works on mine. For now, just install the latest.
Updated the `foundryup` call at the end of the `Dockerfile.foundry` build.
> fix: Don't pin version for foundryup

- .gas-snapshot
- src/KeyRegistry.sol
- src/validators/SignedKeyRequestValidator.sol
- test/Deploy/Deploy.t.sol
- test/KeyRegistry/KeyRegistry.integration.t.sol
- test/KeyRegistry/KeyRegistry.t.sol
- test/KeyRegistry/KeyRegistryTestHelpers.sol
- test/validators/SignedKeyRequestValidator/SignedKeyRequestValidator.t.sol
Now that adding key metadata requires a unique signature per key, we need to add metadata to the batch migration functions.
Update `bulkAddKeysForMigration` add to include per-key metadata in each batch. Refactor to struct args for both `bulkAddKeysForMigration` and `bulkAddKeysForMigration`, instead of separate data arrays.
- Creating these batch structs in tests is painful, since they include arrays of items that need to be initialized an manipulated separately. I've added a couple builder libraries in `KeyRegistryTestHelpers` that make it easier to construct batches in tests.
> fix: add metadata to KeyRegistry batches
